### PR TITLE
Create Android.mk

### PR DESCRIPTION
**Pull request by namkazt**
Add android.mk to build for android

My path is : dragonbones/project/proj.android/Android.mk
edit as your path

i think we should rearrange folder struct. like :

dragonbones/... source
dragonbones/project/proj.android
dragonbones/project/proj.win32
dragonbones/project/.. source of cocos2d-x implement

### CODE REVIEW

**Comment by akdcl** [comment]
Hi, how about folder struct like :

Cocos2DX_3.x/Demos/Classes/proj.android/Android.mk

**Comment by namkazt** [comment]
Here is where i just put dragonbones in cocos2d-x: 
like old struct on cocos2d-x: 
cocos2d/cocos/editor-support/dragonbones/....
this is the good place to put dragonbones.
all src can be put inside that folder.
the implement can put on demo folder or anything you want as struct
.../dragonbones/demo/proj.android/...
.../dragonbones/demo/proj.win32/...

if you agree with that i will create pull request for this

**Comment by akdcl** [comment]
How about folder struct like this?

In cocos2d-x: 
cocos2d-x-3.x/external/dragonBones/... source
cocos2d-x-3.x/external/dragonBones/cocos2dx/... source of cocos2d-x implement
cocos2d-x-3.x/external/dragonBones/proj.android/...
cocos2d-x-3.x/external/dragonBones/proj.win32/...

In github: 
DragonBonesCPP/DragonBones/src/dragonBones/... source
DragonBonesCPP/Cocos2DX_3.x/src/dragonBones/cocos2dx/... source of cocos2d-x implement
DragonBonesCPP/Cocos2DX_3.x/src/dragonBones/proj.android/...
DragonBonesCPP/Cocos2DX_3.x/src/dragonBones/proj.win32/...

**Comment by namkazt** [comment]
look good.

**Pull request merged**
